  name: cicd for devopified projects
  on:
    push:
      branches:
        - feature
      paths-ignore:
       - 'helm/**'
       - 'k8s/**'
       - 'README.md'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up go 1.23
          uses: actions/setup-go@v5
          with:
            go-version: 1.23
        - name: Build
          run: |
            go build -o go-web-app 
        - name: Run Tests
          run: |
            go test ./...
    code-quality:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4


        - name: Set up go 1.23
          uses: actions/setup-go@v5
          with:
            go-version: 1.23
       # - name: Install golangci-lint
       #   run: |
       #     curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.2
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v9
          with:
            version: v2.6
    push:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devopsified:${{ github.run_id }}              

    update-new-tags-in-helm-chart:
      runs-on: ubuntu-latest
      needs: push
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}
            

        - name: Update Helm Chart with new image tag
          run: |
            IMAGE_TAG=${{ github.run_id }}
            sed -i "s/tag: .*/tag: ${{ github.run_id }}/g" /helm/go-chart/values.yaml
            cat /helm/go-chart/values.yaml

        - name: Commit and Push changes
          run: |
            git config --global user.name "RAM28EC"
            git config --global user.email "ram.28ec@gmail.com"  
            git add /helm/go-chart/values.yaml
            git commit -m "Update image tag to ${{ github.run_id }}"
            git push origin feature