- name: cicd for devopified projects
  on:
    push:
      branches:
        - feature
      paths-ignore:
       - 'helm/**'
       - 'k8s/**'
       - 'README.md'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up go 1.22
          uses: actions/setup-go@v5
          with:
            go-version: 1.22
        - name: Build
          run: |
            go build -o go-web-app 
        - name: Run Tests
          run: |
            go test ./...

          